<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>statekeep</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StateKeep</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../../apps/**/*.yaml" LinkBase="apps" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../apps/**/*.yml" LinkBase="apps" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
